### PR TITLE
Get-testFromFile not able to handle -fixture parameter

### PR DESCRIPTION
**Pull request by ambsoerensen**
PR refactors the function Get-TestFromfile. Issue #17 
the funtion now returns the value of the Name parameter regardless of other parameters, their order and whether or not the parameters are named.

Instead of counting tokens the function look at AST types to find the argument for the Name Parameter.

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/operation-validation-framework/18)

### CODE REVIEW

**Comment by devblackops** [comment]
@GitAMBS Perhaps we should validate your changes to `Get-TestFromScript` jive with mine in PR #16. I've modified `Get-TestFromScript` to use AST as well but to add support for Pester tags.

**Comment by ambsoerensen** [comment]
@devblackops Definitely. 

Just looked through your changes. 

If i am not mistaken we should be able to insert the changes in my PR #18 into OperationValidation.psm1 [Line 92](https://github.com/devblackops/Operation-Validation-Framework/blob/e8540d007eabeb33440036f7576c28779ed0d6ce/Modules/OperationValidation/OperationValidation.psm1#L92) from your PR #16.

**Comment by devblackops** [comment]
@GitAMBS I've merged my changes in PR #16. This has caused a conflict with this PR. Can you do a quick edit to your branch to accommodate the changes to the function?  Once that is done I'll merge this in.

**Comment by ambsoerensen** [comment]
Hi @devblackops 

Conflict resolved.

**Comment by ambsoerensen** [comment]
modified the Comprehensive example test to include `-fixture` and `-name` to test the changes. 

Fix an issue with the output test case in [OperationValidation.Tests.ps1](https://github.com/GitAMBS/Operation-Validation-Framework/blob/a2211cc59e42f5aed71a3cf540173e38a0cf2981/Modules/OperationValidation/Test/OperationValidation.Tests.ps1#L76).
as a result the Comprehensive test did not get validated.

**Review by devblackops — CHANGES_REQUESTED** [review]
It looks like you merged an old version of master into your fork which has caused some newer additions (related to module versions, tags, etc.) to be removed. This will have to be cleaned up before we can merge. The easiest and perhaps cleanest thing to do at this point is for you to capture the desired changes to address the -Fixture parameter offline, re-clone https://github.com/PowerShell/Operation-Validation-Framework.git, create a branch for the changes, re-add the changes you captured offline, and submit a new PR.

**Comment by ambsoerensen** [comment]
Thanks for the suggestion @devblackops 

Reforked and committed in PR #25

**Pull request closed without merging**
